### ISSUE TITLE
KiwiIRC ssl 

### ISSUE THREAD

**Issue by blackleakz** [kiwiirc/kiwiirc#1486]
Something went wrong with the ssl config, could you explain how to get it work?
my config.js : 
// Example SSL server block
conf.servers.push({
    port:     7777,
    address: "0.0.0.0",

    ssl:   true,
    ssl_key: "/home/kiwi/KiwiIRC/server.key",
    ssl_cert: "/home/kiwi/KiwiIRC/cert.pem"
});

Error:
/home/kiwi/KiwiIRC/node_modules/daemonize2/lib/daemonize.js:136
            throw new Error(msg.error);
            ^

Error: Error: ENOENT: no such file or directory, open '/home/kiwi/KiwiIRC/cert.pem'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at new module.exports (/home/kiwi/KiwiIRC/server/weblistener.js:43:22)
    at /home/kiwi/KiwiIRC/server/kiwi.js:277:18
    at arrayEach (/home/kiwi/KiwiIRC/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/home/kiwi/KiwiIRC/node_modules/lodash/index.js:3345:13)
    at Object.<anonymous> (/home/kiwi/KiwiIRC/server/kiwi.js:251:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at ChildProcess.<anonymous> (/home/kiwi/KiwiIRC/node_modules/daemonize2/lib/daemonize.js:136:19)
    at ChildProcess.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ItsOnlyBinary** [comment]
Seems you are trying to use old outdated and no longer supported kiwi from https://github.com/prawnsalad/KiwiIRC/

I suggest trying the new kiwiirc
packages: https://kiwiirc.com/downloads
source: https://github.com/kiwiirc/kiwiirc/ (client) && https://github.com/kiwiirc/webircgateway/ (server side)

**Comment by blackleakz** [comment]
Ok, i will try :) thnx
