### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by legendskyk** [kiwiirc/kiwiirc#1878]
Hello,
I am getting this error while run build:

> kiwiirc@1.7.1 build
> vue-cli-service build --no-module

⠧  Building for production...

 ERROR  Failed to compile with 1 error                                4:59:14 PM

Syntax Error: TypeError: eslint.CLIEngine is not a constructor

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /home/kiwiirc/kiwiirc/node_modules/@vue/cli-service/lib/commands/build/in                          dex.js:207:23
    at /home/kiwiirc/kiwiirc/node_modules/webpack/lib/webpack.js:168:8
    at /home/kiwiirc/kiwiirc/node_modules/webpack/lib/HookWebpackError.js:67:2
    at Hook.eval [as callAsync] (eval at create (/home/kiwiirc/kiwiirc/node_modu                          les/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/kiwiirc/kiwiirc/node_modu                          les/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/home/kiwiirc/kiwiirc/node_modules/webpack/lib/Cache.js:1                          54:23)
    at /home/kiwiirc/kiwiirc/node_modules/webpack/lib/Compiler.js:1377:15
    at Hook.eval [as callAsync] (eval at create (/home/kiwiirc/kiwiirc/node_modu                          les/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/kiwiirc/kiwiirc/node_modu                          les/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/home/kiwiirc/kiwiirc/node_modules/webpack/lib/Compiler.j                          s:1370:23)

**Comment by ItsOnlyBinary** [comment]
I suspect you used npm rather than yarn/yarnpkg to download the dependencies and attempt the build.

If I'm correct you will need to remove node_modules then try again using yarn/yarnpkg

**Comment by legendskyk** [comment]
yes i did installation successfull but now avatar plugin give error in yarn build i did msg you on that link kindly see there.
