### ISSUE TITLE
yarn install --production && yarn run build fails

### ISSUE THREAD

**Issue by keydon** [kiwiirc/kiwiirc#886]
Executed commands:
```
yarn install --production
yarn run build
```
First I got this error:
```
yarn run v1.10.1
$ node build/build.js
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/build/check-versions.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn run build' returned a non-zero code: 1
```

after fixing that by moving `semver` up to the `dependecies` i got another error:
```
ERROR in /src/main.js
Module build failed: Error: Cannot read config file: /.eslintrc.js
Error: Cannot find module 'eslint-plugin-rulesdir'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/.eslintrc.js:1:86)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (/node_modules/require-uncached/index.js:28:9)
    at loadJSConfigFile (/node_modules/eslint/lib/config/config-file.js:154:16)
    at loadConfigFile (/node_modules/eslint/lib/config/config-file.js:209:22)
    at loadFromDisk (/node_modules/eslint/lib/config/config-file.js:486:18)
 @ multi core-js/fn/promise ../src/main.js

  Build failed with errors.

error Command failed with exit code 1.
```

In summary as a quickfix I had to move
* eslint-plugin-rulesdir
* semver

from `devDepenencies` to actual `dependencies` in order to get it to build in production mode.
Even though I dont think that eslint packages should be part of the production build artifact.

**Comment by prawnsalad** [comment]
Good catch. Eslint is used just before any type of build to catch any errors that may have been introduced during a quick production patch (a few people seem to do this live and then wonder why errors happen...)
